Pandas is an open-source Python library used for data manipulation, analysis and cleaning. It provides fast and flexible tools to work with tabular data, similar to spreadsheets or SQL tables.
Installation
Before using Pandas, make sure it is installed:
pip install pandas

After the Pandas have been installed in the system we need to import the library. This module is imported using:
import pandas as pd

Pandas Series 
A Pandas Series is a one-dimensional labeled array capable of holding data of any type such as integers, floats, strings, or objects.

It is similar to a single column in a table or spreadsheet.

In simple words:

Series = Data + Index (labels)

In [ ]:
# Series from List
import pandas as pd
data =[10,20,30,40,50]
s=pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
# Series with Custom Index
import pandas as pd
data=[10,20,30,40,50]
s=pd.Series(data,index=["a","b","c","d","e"])
print(s)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [ ]:
# Series from Dictionary
import pandas as pd
data={
    "maths":60,
    "science":70,
    "gujrati":50
    }
s=pd.Series(data)
print(s)

maths      60
science    70
gujrati    50
dtype: int64

In [ ]:
# Accessing Elements in Series
import pandas as pd
data={
    "maths":60,
    "science":70,
    "gujrati":50,
    "english":80,
    "hindi":55,
    "social science":68
    }
dic=pd.Series(data)
print(dic)
print(dic["gujrati"])
print(dic[0:4])

maths             60
science           70
gujrati           50
english           80
hindi             55
social science    68
dtype: int64
50
maths      60
science    70
gujrati    50
english    80
dtype: int64

In [ ]:
# Series Attributes
import pandas as pd
data={
    "maths":60,
    "science":70,
    "gujrati":50,
    "english":80,
    "hindi":55,
    "social science":68
    }
dic=pd.Series(data)
print(dic)
# dic.values show the values
print(dic.values)
# .index show the index
print(dic.index)
# .dtype show the data type
print(dic.dtype)
# .shape show the  number of elements.
print(dic.shape)

maths             60
science           70
gujrati           50
english           80
hindi             55
social science    68
dtype: int64
[60 70 50 80 55 68]
Index(['maths', 'science', 'gujrati', 'english', 'hindi', 'social science'], dtype='object')
int64
(6,)

In [ ]:
# Mathematical Operations on Series
import pandas as pd
s=pd.Series([10,20,30,40,50])
print(s + 5)
print(s * 2)
print(s - 5)
print(s / 2)

0    15
1    25
2    35
3    45
4    55
dtype: int64
0     20
1     40
2     60
3     80
4    100
dtype: int64
0     5
1    15
2    25
3    35
4    45
dtype: int64
0     5.0
1    10.0
2    15.0
3    20.0
4    25.0
dtype: float64

In [ ]:
# Conditional Selection
import pandas as pd
s=pd.Series([200,300,400,500,600])
print(s[s > 300])

2    400
3    500
4    600
dtype: int64

In [ ]:
# Basic Statistical Functions
import pandas as pd
s=pd.Series([10,15,20,25,30,35,40,45,50])
print(s.mean())
print(s.max())
print(s.min())

30.0
50
10

In [ ]:
# Updating Values & Deleting values
s = pd.Series([10,20,30])
s[1] = 50
print(s)
s.drop(1)

0    10
1    50
2    30
dtype: int64

0    10
2    30
dtype: int64

Pandas DataFrame 

A Pandas DataFrame is a two-dimensional data structure used to store data in rows and columns, similar to an Excel spreadsheet, SQL table, or CSV file.

It is the most important data structure in Pandas and is widely used in data analysis and machine learning.

Simple Definition 

A DataFrame is a two-dimensional labeled data structure in Pandas that contains rows and columns and can store data of different types.

In [ ]:
# Create DataFrame from List
import pandas as pd
data=[[10,20,30],[40,50,60],[70,80,90]]
df=pd.DataFrame(data)
print(df)

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [ ]:
# Create DataFrame from Dictionary
import pandas as pd
data = {
    "Name": ["Ram", "Shyam", "Riya"],
    "Age": [20, 21, 19],
    "City": ["Delhi", "Mumbai", "Pune"]
}
df = pd.DataFrame(data)
print(df)

    Name  Age    City
0    Ram   20   Delhi
1  Shyam   21  Mumbai
2   Riya   19    Pune

In [ ]:
# selecting the data
import pandas as pd
data = {
    "Name": ["Ram", "Shyam", "Riya"],
    "Age": [20, 21, 19],
    "City": ["Delhi", "Mumbai", "Pune"]
}
df = pd.DataFrame(data)
print(df)
print("____________________")
print(df["Name"])
print("____________________")
print(df[["Name","Age"]])
print("____________________")
print(df.iloc[0])
print("____________________")
print(df.loc[1])

    Name  Age    City
0    Ram   20   Delhi
1  Shyam   21  Mumbai
2   Riya   19    Pune
____________________
0      Ram
1    Shyam
2     Riya
Name: Name, dtype: object
____________________
    Name  Age
0    Ram   20
1  Shyam   21
2   Riya   19
____________________
Name      Ram
Age        20
City    Delhi
Name: 0, dtype: object
____________________
Name     Shyam
Age         21
City    Mumbai
Name: 1, dtype: object
____________________
    Name  Age    City
1  Shyam   21  Mumbai
    Name  Age    City  Salary
0    Ram   20   Delhi   20000
1  Shyam   21  Mumbai   25000
2   Riya   19    Pune   22000
____________________
    Name  Age    City  Salary
0    Ram   25   Delhi   20000
1  Shyam   21  Mumbai   25000
2   Riya   19    Pune   22000

In [ ]:
#Filtering Data
import pandas as pd
data = {
    "Name": ["Ram", "Shyam", "Riya"],
    "Age": [20, 21, 19],
    "City": ["Delhi", "Mumbai", "Pune"]
}
df = pd.DataFrame(data)
print(df)
print("____________________")
print(df[df["Age"] > 20])
print("____________________")
df["Salary"] = [20000,25000,22000]
print(df)
print("____________________")
df.loc[0,"Age"] = 25
print(df)
df.drop("Salary", axis=1)

    Name  Age    City
0    Ram   20   Delhi
1  Shyam   21  Mumbai
2   Riya   19    Pune
____________________
    Name  Age    City
1  Shyam   21  Mumbai
____________________
    Name  Age    City  Salary
0    Ram   20   Delhi   20000
1  Shyam   21  Mumbai   25000
2   Riya   19    Pune   22000
____________________
    Name  Age    City  Salary
0    Ram   25   Delhi   20000
1  Shyam   21  Mumbai   25000
2   Riya   19    Pune   22000

    Name  Age    City
0    Ram   25   Delhi
1  Shyam   21  Mumbai
2   Riya   19    Pune

In [ ]:
# shorting  data
import pandas as pd
data = {
    "Name": ["Ram", "Shyam", "Riya"],
    "Age": [20, 21, 19],
    "City": ["Delhi", "Mumbai", "Pune"]
}
df = pd.DataFrame(data)
print(df.sort_values("Age"))
print("____________________")
print(df.sort_values("Age", ascending=False))

    Name  Age    City
2   Riya   19    Pune
0    Ram   20   Delhi
1  Shyam   21  Mumbai
____________________
    Name  Age    City
1  Shyam   21  Mumbai
0    Ram   20   Delhi
2   Riya   19    Pune

important operations in Pandas. These are commonly used when working with datasets in Python.
1. Loading Data:Loading Data
Loading data means importing data from files such as CSV, Excel, JSON, or databases into a Pandas DataFrame so it can be analyzed.
2. Viewing and Exploring Data:After loading the dataset, we need to view and understand the data structure.
3. Handling Missing Data:Missing data occurs when some values are empty or null.
4. Selecting and Filtering Data:Selecting data means choosing specific rows or columns.
5. Adding and Removing Columns:Columns can be added or removed easily in Pandas.
6. Grouping Data (GroupBy):The groupby() function groups data based on column values and performs operations like sum, mean, count.

In [ ]:
import pandas as pd

df = pd.read_csv("student_performance_updated_1000.csv")
print(df)

     StudentID            Name  Gender  AttendanceRate  StudyHoursPerWeek  \
0          1.0            John    Male            85.0               15.0
1          2.0           Sarah  Female            90.0               20.0
2          3.0            Alex    Male            78.0               10.0
3          4.0         Michael    Male            92.0               25.0
4          5.0            Emma  Female             NaN               18.0
..         ...             ...     ...             ...                ...
995        NaN  Kenneth Murray    Male            85.0               20.0
996     4497.0       Amy Stout  Female            91.0                NaN
997     1886.0             NaN    Male            85.0                8.0
998     7636.0  Joseph Sherman    Male            88.0               17.0
999     8021.0     Maria Walls  Female            88.0               10.0

     PreviousGrade  ExtracurricularActivities ParentalSupport  FinalGrade  \
0             78.0                        1.0            High        80.0
1             85.0                        2.0          Medium        87.0
2             65.0                        0.0             Low        68.0
3             90.0                        3.0            High        92.0
4             82.0                        2.0          Medium        85.0
..             ...                        ...             ...         ...
995            NaN                        1.0            High        72.0
996           86.0                        0.0            High        90.0
997           82.0                        2.0             Low        68.0
998           60.0                        2.0            High        85.0
999           90.0                        1.0          Medium         NaN

     Study Hours  Attendance (%) Online Classes Taken
0            4.8            59.0                False
1            2.2            70.0                 True
2            4.6            92.0                False
3            2.9            96.0                False
4            4.1            97.0                 True
..           ...             ...                  ...
995          0.8            80.0                 True
996          3.9            80.0                 True
997          0.4            54.0                False
998          0.9            53.0                 True
999          2.4            94.0                 True

[1000 rows x 12 columns]

In [ ]:
# Shows the first 5 records.
import pandas as pd
df = pd.read_csv("student_performance_updated_1000.csv")
df.head()

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True

In [ ]:
# Shows the last 5 records.
import pandas as pd
df = pd.read_csv("student_performance_updated_1000.csv")
df.tail()

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
995,NaN,Kenneth Murray,Male,85.0,20.0,NaN,1.0,High,72.0,0.8,80.0,True
996,4497.0,Amy Stout,Female,91.0,NaN,86.0,0.0,High,90.0,3.9,80.0,True
997,1886.0,NaN,Male,85.0,8.0,82.0,2.0,Low,68.0,0.4,54.0,False
998,7636.0,Joseph Sherman,Male,88.0,17.0,60.0,2.0,High,85.0,0.9,53.0,True
999,8021.0,Maria Walls,Female,88.0,10.0,90.0,1.0,Medium,NaN,2.4,94.0,True

In [ ]:
# Dataset information
import pandas as pd
df = pd.read_csv("student_performance_updated_1000.csv")
df.info()
# df.columns
# df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  960 non-null    float64
 1   Name                       966 non-null    object
 2   Gender                     952 non-null    object
 3   AttendanceRate             960 non-null    float64
 4   StudyHoursPerWeek          950 non-null    float64
 5   PreviousGrade              967 non-null    float64
 6   ExtracurricularActivities  957 non-null    float64
 7   ParentalSupport            978 non-null    object
 8   FinalGrade                 960 non-null    float64
 9   Study Hours                976 non-null    float64
 10  Attendance (%)             959 non-null    float64
 11  Online Classes Taken       975 non-null    object
dtypes: float64(8), object(4)
memory usage: 93.9+ KB

In [ ]:
# Shows statistics such as:
# mean
# minimum
# maximum
# standard deviation
df.describe()

,StudentID,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,FinalGrade,Study Hours,Attendance (%)
count,960.000000,960.000000,950.000000,967.000000,957.000000,960.000000,976.000000,959.000000
mean,5416.019792,85.510417,17.630526,77.598759,1.520376,80.030208,2.406967,77.248175
std,2653.748319,7.332125,6.272132,10.006640,1.046439,9.493652,1.620267,19.298148
min,1.000000,70.000000,8.000000,60.000000,0.000000,62.000000,-5.000000,50.000000
25%,3113.500000,82.000000,12.000000,70.000000,1.000000,72.000000,1.200000,63.000000
50%,5396.500000,88.000000,18.000000,78.000000,1.000000,80.000000,2.500000,76.000000
75%,7754.750000,91.000000,22.000000,86.000000,2.000000,88.000000,3.700000,89.000000
max,9998.000000,95.000000,30.000000,90.000000,3.000000,92.000000,5.000000,200.000000

In [ ]:
df.isnull()

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
995,True,False,False,False,False,True,False,False,False,False,False,False
996,False,False,False,False,True,False,False,False,False,False,False,False
997,False,True,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,True,False,False,False

In [ ]:
df.isnull().sum()

StudentID                    40
Name                         34
Gender                       48
AttendanceRate               40
StudyHoursPerWeek            50
PreviousGrade                33
ExtracurricularActivities    43
ParentalSupport              22
FinalGrade                   40
Study Hours                  24
Attendance (%)               41
Online Classes Taken         25
dtype: int64

In [ ]:
# Handling Missing Values Using read_csv
# The na_values parameter replaces specified strings (e.g., "N/A", "Unknown") with NaN, enabling consistent handling of missing or incomplete data during analysis.\
import pandas as pd

df = pd.read_csv("student_performance_updated_1000.csv", na_values=["N/A", "Unknown"])
print(df.head())

   StudentID     Name  Gender  AttendanceRate  StudyHoursPerWeek  \
0        1.0     John    Male            85.0               15.0
1        2.0    Sarah  Female            90.0               20.0
2        3.0     Alex    Male            78.0               10.0
3        4.0  Michael    Male            92.0               25.0
4        5.0     Emma  Female             NaN               18.0

   PreviousGrade  ExtracurricularActivities ParentalSupport  FinalGrade  \
0           78.0                        1.0            High        80.0
1           85.0                        2.0          Medium        87.0
2           65.0                        0.0             Low        68.0
3           90.0                        3.0            High        92.0
4           82.0                        2.0          Medium        85.0

   Study Hours  Attendance (%) Online Classes Taken
0          4.8            59.0                False
1          2.2            70.0                 True
2          4.6            92.0                False
3          2.9            96.0                False
4          4.1            97.0                 True

fillna() used to replace missing values (NaN) with a given value.

In [ ]:
# Fill NaN Values with 'No Gender'
import pandas as pd

d = pd.read_csv("student_performance_updated_1000.csv")
# d["Gender"].fillna("No Gender", inplace=True)
d.fillna({"Gender":"No Gender"},inplace=True)
print(d[10:25])

    StudentID               Name     Gender  AttendanceRate  \
10     2824.0   Shannon Harrison       Male            88.0
11     7912.0       Peter Davila       Male            85.0
12     4611.0     Katherine Gray     Female            91.0
13     6514.0       Megan Miller       Male            90.0
14        NaN     James Williams       Male            70.0
15     2139.0  Derrick Alexander       Male             NaN
16        NaN     Courtney Clark  No Gender            95.0
17     8573.0        James Smith     Female            88.0
18     5386.0     James Reynolds       Male            92.0
19     3340.0    Brittany Sutton     Female            78.0
20     6930.0     Annette Medina       Male            78.0
21     2040.0       James Duncan     Female            70.0
22     9797.0       Donna Taylor     Female            95.0
23     9201.0    David Robertson       Male            82.0
24     9837.0        Susan Brown       Male            91.0

    StudyHoursPerWeek  PreviousGrade  ExtracurricularActivities  \
10               25.0           90.0                        0.0
11               20.0            NaN                        3.0
12               18.0           78.0                        0.0
13                8.0           85.0                        1.0
14               20.0           70.0                        2.0
15               18.0           85.0                        3.0
16               25.0           82.0                        2.0
17               12.0           90.0                        1.0
18               22.0           88.0                        3.0
19               25.0           70.0                        2.0
20               12.0           77.0                        2.0
21               22.0           77.0                        2.0
22               20.0           82.0                        NaN
23               20.0           82.0                        NaN
24               30.0           77.0                        1.0

   ParentalSupport  FinalGrade  Study Hours  Attendance (%)  \
10             NaN        87.0          3.4            84.0
11             Low        88.0          0.1            62.0
12             Low        62.0          1.7            59.0
13          Medium        88.0          1.3            52.0
14             Low        88.0          4.4            73.0
15            High        62.0          1.4            90.0
16             Low        68.0          2.7            65.0
17            High        92.0          4.1            70.0
18             Low        78.0          2.0            91.0
19          Medium        88.0          2.1            87.0
20            High        87.0          0.8            60.0
21          Medium        72.0          4.3            50.0
22            High        78.0          0.0            96.0
23             Low         NaN          0.8            98.0
24            High        90.0          4.4            69.0

   Online Classes Taken
10                 True
11                False
12                 True
13                False
14                 True
15                False
16                 True
17                False
18                False
19                False
20                False
21                 True
22                False
23                 True
24                 True

Fill with Next Value (Backward Fill)

The bfill function is used to fill it with the next value.

df.fillna(method='pad')

Fill with Previous Value (Forward Fill)

The pad method is used to fill missing values with the previous value. 

df.fillna(method='bfill')

In [ ]:
import pandas as pd

pd.set_option('future.no_silent_downcasting', True)

d = pd.read_csv("student_performance_updated_1000.csv")

# d = d.bfill()
d = d.ffill()
print(d)

     StudentID            Name  Gender  AttendanceRate  StudyHoursPerWeek  \
0          1.0            John    Male            85.0               15.0
1          2.0           Sarah  Female            90.0               20.0
2          3.0            Alex    Male            78.0               10.0
3          4.0         Michael    Male            92.0               25.0
4          5.0            Emma  Female            92.0               18.0
..         ...             ...     ...             ...                ...
995     2787.0  Kenneth Murray    Male            85.0               20.0
996     4497.0       Amy Stout  Female            91.0               20.0
997     1886.0       Amy Stout    Male            85.0                8.0
998     7636.0  Joseph Sherman    Male            88.0               17.0
999     8021.0     Maria Walls  Female            88.0               10.0

     PreviousGrade  ExtracurricularActivities ParentalSupport  FinalGrade  \
0             78.0                        1.0            High        80.0
1             85.0                        2.0          Medium        87.0
2             65.0                        0.0             Low        68.0
3             90.0                        3.0            High        92.0
4             82.0                        2.0          Medium        85.0
..             ...                        ...             ...         ...
995           60.0                        1.0            High        72.0
996           86.0                        0.0            High        90.0
997           82.0                        2.0             Low        68.0
998           60.0                        2.0            High        85.0
999           90.0                        1.0          Medium        85.0

     Study Hours  Attendance (%) Online Classes Taken
0            4.8            59.0                False
1            2.2            70.0                 True
2            4.6            92.0                False
3            2.9            96.0                False
4            4.1            97.0                 True
..           ...             ...                  ...
995          0.8            80.0                 True
996          3.9            80.0                 True
997          0.4            54.0                False
998          0.9            53.0                 True
999          2.4            94.0                 True

[1000 rows x 12 columns]

In [ ]:
# Use replace() function to replace NaN values with a specific value.
import pandas as pd
d = pd.read_csv("student_performance_updated_1000.csv")
d["Gender"]=d["Gender"].replace("Male","M")
print(d.head())

   StudentID     Name  Gender  AttendanceRate  StudyHoursPerWeek  \
0        1.0     John       M            85.0               15.0
1        2.0    Sarah  Female            90.0               20.0
2        3.0     Alex       M            78.0               10.0
3        4.0  Michael       M            92.0               25.0
4        5.0     Emma  Female             NaN               18.0

   PreviousGrade  ExtracurricularActivities ParentalSupport  FinalGrade  \
0           78.0                        1.0            High        80.0
1           85.0                        2.0          Medium        87.0
2           65.0                        0.0             Low        68.0
3           90.0                        3.0            High        92.0
4           82.0                        2.0          Medium        85.0

   Study Hours  Attendance (%) Online Classes Taken
0          4.8            59.0                False
1          2.2            70.0                 True
2          4.6            92.0                False
3          2.9            96.0                False
4          4.1            97.0                 True

In [ ]:
import pandas as pd
d = pd.read_csv("student_performance_updated_1000.csv")
print(d["StudyHoursPerWeek"])

0      15.0
1      20.0
2      10.0
3      25.0
4      18.0
       ...
995    20.0
996     NaN
997     8.0
998    17.0
999    10.0
Name: StudyHoursPerWeek, Length: 1000, dtype: float64

In [4]:
# interpolate() is used to fill missing values (NaN) by estimating values between existing data points. 
# It works best with numeric columns.
import pandas as pd

df = pd.read_csv("student_performance_updated_1000.csv")

# df = df.interpolate()
df["StudyHoursPerWeek"] = df["StudyHoursPerWeek"].interpolate()

print(df["StudyHoursPerWeek"])

0      15.0
1      20.0
2      10.0
3      25.0
4      18.0
       ...
995    20.0
996    14.0
997     8.0
998    17.0
999    10.0
Name: StudyHoursPerWeek, Length: 1000, dtype: float64

In [3]:
# The dropna() function used to removes rows or columns with NaN values. 
# It can be used to drop data based on different conditions.
import pandas as pd

df = pd.read_csv("student_performance_updated_1000.csv")
# Remove Rows with Missing Values
df = df.dropna()
print(df)
# Remove Rows if a Specific Column Has Missing Values
df = df.dropna(subset=["Gender"])
print(df)
# Remove Columns with Missing Values
df = df.dropna(axis=1)
# Drop Rows with All Values Missing
df = df.dropna(how="all")
# Drop Rows with Any Missing Values
df = df.dropna(how="any")

     StudentID            Name  Gender  AttendanceRate  StudyHoursPerWeek  \
0          1.0            John    Male            85.0               15.0
1          2.0           Sarah  Female            90.0               20.0
2          3.0            Alex    Male            78.0               10.0
3          4.0         Michael    Male            92.0               25.0
6          7.0          Daniel    Male            70.0                8.0
..         ...             ...     ...             ...                ...
989     2116.0   Kimberly Pena  Female            91.0               30.0
991     7701.0   Anna Martinez    Male            85.0               30.0
993     3592.0  Monica Johnson  Female            90.0               25.0
994     2787.0  Shannon Porter    Male            78.0               20.0
998     7636.0  Joseph Sherman    Male            88.0               17.0

     PreviousGrade  ExtracurricularActivities ParentalSupport  FinalGrade  \
0             78.0                        1.0            High        80.0
1             85.0                        2.0          Medium        87.0
2             65.0                        0.0             Low        68.0
3             90.0                        3.0            High        92.0
6             60.0                        0.0             Low        62.0
..             ...                        ...             ...         ...
989           88.0                        2.0            High        68.0
991           70.0                        3.0          Medium        90.0
993           60.0                        1.0             Low        87.0
994           60.0                        0.0            High        62.0
998           60.0                        2.0            High        85.0

     Study Hours  Attendance (%) Online Classes Taken
0            4.8            59.0                False
1            2.2            70.0                 True
2            4.6            92.0                False
3            2.9            96.0                False
6            4.5            96.0                False
..           ...             ...                  ...
989          3.6            79.0                False
991          0.4            76.0                False
993          1.7            79.0                False
994          1.6            70.0                False
998          0.9            53.0                 True

[645 rows x 12 columns]
     StudentID            Name  Gender  AttendanceRate  StudyHoursPerWeek  \
0          1.0            John    Male            85.0               15.0
1          2.0           Sarah  Female            90.0               20.0
2          3.0            Alex    Male            78.0               10.0
3          4.0         Michael    Male            92.0               25.0
6          7.0          Daniel    Male            70.0                8.0
..         ...             ...     ...             ...                ...
989     2116.0   Kimberly Pena  Female            91.0               30.0
991     7701.0   Anna Martinez    Male            85.0               30.0
993     3592.0  Monica Johnson  Female            90.0               25.0
994     2787.0  Shannon Porter    Male            78.0               20.0
998     7636.0  Joseph Sherman    Male            88.0               17.0

     PreviousGrade  ExtracurricularActivities ParentalSupport  FinalGrade  \
0             78.0                        1.0            High        80.0
1             85.0                        2.0          Medium        87.0
2             65.0                        0.0             Low        68.0
3             90.0                        3.0            High        92.0
6             60.0                        0.0             Low        62.0
..             ...                        ...             ...         ...
989           88.0                        2.0            High        68.0
991           70.0                        3.0          Medium        90.0
993           60.0                        1.0             Low        87.0
994           60.0                        0.0            High        62.0
998           60.0                        2.0            High        85.0

     Study Hours  Attendance (%) Online Classes Taken
0            4.8            59.0                False
1            2.2            70.0                 True
2            4.6            92.0                False
3            2.9            96.0                False
6            4.5            96.0                False
..           ...             ...                  ...
989          3.6            79.0                False
991          0.4            76.0                False
993          1.7            79.0                False
994          1.6            70.0                False
998          0.9            53.0                 True

[645 rows x 12 columns]

String Manipulations 

String manipulation refers to cleaning, transforming, and processing text data so it becomes suitable for analysis. Pandas provides a wide collection of .str functions that make it easy to work with string columns inside a DataFrame such as converting cases, trimming spaces, splitting, extracting patterns, replacing values, and more.

In [ ]:
import pandas as pd
df = pd.read_csv("student_performance_updated_1000.csv")
print(df)
print(df.astype('string'))

     StudentID            Name  Gender  AttendanceRate  StudyHoursPerWeek  \
0          1.0            John    Male            85.0               15.0
1          2.0           Sarah  Female            90.0               20.0
2          3.0            Alex    Male            78.0               10.0
3          4.0         Michael    Male            92.0               25.0
4          5.0            Emma  Female             NaN               18.0
..         ...             ...     ...             ...                ...
995        NaN  Kenneth Murray    Male            85.0               20.0
996     4497.0       Amy Stout  Female            91.0                NaN
997     1886.0             NaN    Male            85.0                8.0
998     7636.0  Joseph Sherman    Male            88.0               17.0
999     8021.0     Maria Walls  Female            88.0               10.0

     PreviousGrade  ExtracurricularActivities ParentalSupport  FinalGrade  \
0             78.0                        1.0            High        80.0
1             85.0                        2.0          Medium        87.0
2             65.0                        0.0             Low        68.0
3             90.0                        3.0            High        92.0
4             82.0                        2.0          Medium        85.0
..             ...                        ...             ...         ...
995            NaN                        1.0            High        72.0
996           86.0                        0.0            High        90.0
997           82.0                        2.0             Low        68.0
998           60.0                        2.0            High        85.0
999           90.0                        1.0          Medium         NaN

     Study Hours  Attendance (%) Online Classes Taken
0            4.8            59.0                False
1            2.2            70.0                 True
2            4.6            92.0                False
3            2.9            96.0                False
4            4.1            97.0                 True
..           ...             ...                  ...
995          0.8            80.0                 True
996          3.9            80.0                 True
997          0.4            54.0                False
998          0.9            53.0                 True
999          2.4            94.0                 True

[1000 rows x 12 columns]
    StudentID            Name  Gender AttendanceRate StudyHoursPerWeek  \
0         1.0            John    Male           85.0              15.0
1         2.0           Sarah  Female           90.0              20.0
2         3.0            Alex    Male           78.0              10.0
3         4.0         Michael    Male           92.0              25.0
4         5.0            Emma  Female           <NA>              18.0
..        ...             ...     ...            ...               ...
995      <NA>  Kenneth Murray    Male           85.0              20.0
996    4497.0       Amy Stout  Female           91.0              <NA>
997    1886.0            <NA>    Male           85.0               8.0
998    7636.0  Joseph Sherman    Male           88.0              17.0
999    8021.0     Maria Walls  Female           88.0              10.0

    PreviousGrade ExtracurricularActivities ParentalSupport FinalGrade  \
0            78.0                       1.0            High       80.0
1            85.0                       2.0          Medium       87.0
2            65.0                       0.0             Low       68.0
3            90.0                       3.0            High       92.0
4            82.0                       2.0          Medium       85.0
..            ...                       ...             ...        ...
995          <NA>                       1.0            High       72.0
996          86.0                       0.0            High       90.0
997          82.0                       2.0             Low       68.0
998          60.0                       2.0            High       85.0
999          90.0                       1.0          Medium       <NA>

    Study Hours Attendance (%) Online Classes Taken
0           4.8           59.0                False
1           2.2           70.0                 True
2           4.6           92.0                False
3           2.9           96.0                False
4           4.1           97.0                 True
..          ...            ...                  ...
995         0.8           80.0                 True
996         3.9           80.0                 True
997         0.4           54.0                False
998         0.9           53.0                 True
999         2.4           94.0                 True

[1000 rows x 12 columns]

String Operations

In [5]:
#  lower()
print(df["Name"].str.lower())

0                john
1               sarah
2                alex
3             michael
4                emma
            ...
995    kenneth murray
996         amy stout
997               NaN
998    joseph sherman
999       maria walls
Name: Name, Length: 1000, dtype: object

In [6]:
# Upper()
print(df["Name"].str.upper())

0                JOHN
1               SARAH
2                ALEX
3             MICHAEL
4                EMMA
            ...
995    KENNETH MURRAY
996         AMY STOUT
997               NaN
998    JOSEPH SHERMAN
999       MARIA WALLS
Name: Name, Length: 1000, dtype: object

In [7]:
# strip():This method removes unwanted leading and trailing spaces from each string to clean the data.
print(df["Name"].str.strip())

0                John
1               Sarah
2                Alex
3             Michael
4                Emma
            ...
995    Kenneth Murray
996         Amy Stout
997               NaN
998    Joseph Sherman
999       Maria Walls
Name: Name, Length: 1000, dtype: object

In [8]:
# split(): This method splits each string into a list of parts based on a given separator.

# " " it means that in between space in the name replace with the ","
print(df["Name"].str.split(" ")) 
# " e " it means that given chracter in the strinf split with ",".
print(df["Gender"].str.split("e"))

0                 [John]
1                [Sarah]
2                 [Alex]
3              [Michael]
4                 [Emma]
             ...
995    [Kenneth, Murray]
996         [Amy, Stout]
997                  NaN
998    [Joseph, Sherman]
999       [Maria, Walls]
Name: Name, Length: 1000, dtype: object
0         [Mal, ]
1      [F, mal, ]
2         [Mal, ]
3         [Mal, ]
4      [F, mal, ]
          ...
995       [Mal, ]
996    [F, mal, ]
997       [Mal, ]
998       [Mal, ]
999    [F, mal, ]
Name: Gender, Length: 1000, dtype: object

In [9]:
# len(): This method calculates and returns the character length of each string in the column.

print(df["Name"].str.len())

0       4.0
1       5.0
2       4.0
3       7.0
4       4.0
       ...
995    14.0
996     9.0
997     NaN
998    14.0
999    11.0
Name: Name, Length: 1000, dtype: float64

In [10]:
#  cat(): This method concatenates all strings in the column into a single string using a chosen separator
print(df["ParentalSupport"].str.cat(sep=","))
print(df["Name"].str.cat(sep="$"))

High,Medium,Low,High,Medium,High,Low,Medium,Low,High,Low,Low,Medium,Low,High,Low,High,Low,Medium,High,Medium,High,Low,High,High,Low,Medium,Medium,Medium,High,High,High,Medium,Low,Low,Low,High,Low,Low,Low,High,Low,Medium,Medium,Low,Medium,Medium,High,High,Low,High,High,Low,High,Medium,High,Medium,High,Medium,High,Low,Low,Medium,High,Medium,High,High,Low,Low,Medium,Medium,Medium,Medium,Medium,Low,Low,Low,Medium,High,High,High,Medium,High,Low,Low,Medium,High,High,Low,Medium,Medium,Medium,High,High,Medium,Low,Medium,Medium,Low,High,Low,Low,Medium,Low,Medium,Medium,Medium,Medium,Medium,High,Medium,High,Low,High,Medium,High,Medium,High,High,High,Low,High,Low,Low,Medium,Medium,Low,Medium,Medium,Medium,Low,Medium,Medium,Medium,High,Low,High,Medium,Low,Low,High,Low,Low,High,Medium,Low,High,Medium,Medium,High,High,Low,High,Medium,Medium,Low,High,Medium,High,Medium,High,Low,Low,Medium,Low,Medium,Medium,Medium,High,Low,Low,High,Low,Low,Medium,High,Low,Medium,Medium,High,Low,Low,Medium,Low,High,Medium,Medium,High,Low,Low,Medium,High,Medium,Medium,Low,High,Low,Medium,High,Medium,Low,Low,High,Medium,Low,High,High,Low,Medium,Medium,High,High,Low,Medium,Medium,High,Medium,Medium,Medium,High,High,Low,Low,Medium,Low,Medium,High,High,Medium,High,Low,Low,High,High,Medium,High,High,Medium,Medium,High,Low,Low,High,High,Low,High,Low,Medium,High,Medium,High,High,Low,Low,Medium,Low,High,High,High,Medium,High,High,Medium,Low,Low,Medium,High,Medium,Medium,Low,High,High,High,High,Medium,Low,Low,Medium,Low,Medium,High,High,Low,Medium,Medium,High,Low,Medium,Low,Medium,Low,High,High,Low,Low,Medium,Medium,Medium,High,Low,High,Low,High,Low,Low,High,Medium,Medium,High,Medium,High,Medium,High,Low,High,Medium,High,High,High,High,High,High,High,Medium,Medium,High,Low,Medium,High,Low,High,High,Low,Medium,High,Low,Low,Low,High,High,Medium,Medium,Low,Medium,Low,High,High,Medium,Medium,Medium,High,Medium,Low,Medium,Medium,Low,Medium,High,Low,Low,Medium,High,Low,Medium,Medium,Low,High,Low,Medium,Low,High,High,Low,Medium,High,Medium,High,High,High,High,Medium,Medium,High,High,Medium,High,Medium,High,Medium,Medium,Low,Low,High,High,Low,High,Low,Medium,High,High,Low,Medium,Low,Medium,High,High,Low,Low,Medium,Low,Low,High,Low,Medium,Medium,High,Medium,Medium,Low,Low,High,High,Low,Low,High,Medium,High,Low,High,Low,High,Low,High,High,High,Low,Low,Low,Low,High,High,Low,Medium,Low,Low,Low,High,Low,High,Medium,High,Medium,High,Medium,Medium,Medium,Low,High,Low,Low,High,High,Medium,Low,Medium,High,High,High,High,Medium,High,High,High,Medium,Low,Medium,Low,Low,High,Low,Medium,High,Medium,Medium,Medium,Medium,Medium,High,High,Medium,High,Low,High,Medium,Medium,Medium,High,Low,Low,High,Low,Low,Low,High,Medium,Low,Low,High,High,Low,Low,Medium,Low,Low,Low,Medium,Low,Medium,Medium,Low,High,High,High,Low,Low,Medium,High,Medium,High,High,Medium,Medium,Medium,High,High,High,Low,Medium,Medium,High,Low,Medium,Low,Medium,High,Low,High,High,Medium,High,High,Medium,Low,High,Medium,High,High,Medium,Low,Low,Medium,Low,Low,Low,High,Low,Medium,Medium,Low,High,High,High,Medium,Low,Medium,High,Low,Low,High,Low,Medium,Medium,Low,Low,High,Low,Low,Medium,Medium,Medium,Low,High,Medium,Low,High,Low,High,Medium,Low,Medium,High,High,Low,Medium,Low,High,Low,Medium,Low,High,Medium,Medium,Low,High,Low,Medium,Low,Low,Low,High,Low,Medium,High,Low,Medium,Medium,High,Medium,Medium,Medium,Medium,High,Medium,High,High,Low,Low,Medium,Medium,Low,Low,High,Medium,Medium,Low,High,High,High,High,High,Low,High,High,Low,High,Low,Low,High,Medium,Low,High,Low,Medium,Low,Low,Medium,Medium,Low,High,High,Medium,High,Medium,High,Medium,Low,Medium,Medium,Medium,Medium,Medium,High,High,Low,Low,Medium,Medium,High,High,Medium,Medium,Low,Low,Medium,High,High,High,Low,Low,Medium,Low,High,Medium,Medium,Medium,Medium,High,Low,High,Low,High,Low,Low,High,High,Low,Medium,Medium,High,Medium,High,High,High,Low,High,Medium,High,Low,Low,High,High,Low,High,Medium,Medium,High,Low,High,Medium,High,High,High,High,Low,Low,Medium,Medium,Medium,Low,Low,High,Medium,Medium,Low,Medium,Medium,High,Low,Low,Low,Low,Low,High,High,High,High,High,Medium,Low,High,Medium,Medium,High,Low,Low,Low,Low,High,Medium,Low,High,Low,Medium,High,Medium,Medium,Low,Low,Low,Low,Medium,Medium,Medium,Medium,Medium,Low,High,Low,Medium,High,High,Medium,High,High,Medium,Medium,Medium,Medium,Medium,Medium,High,Low,Medium,Low,High,Medium,High,High,High,Low,High,Medium,Medium,Low,High,Low,Low,High,High,Low,High,Medium,Medium,High,High,High,Medium,Medium,Medium,Medium,Medium,High,Low,Low,Low,High,Low,Medium,Low,Low,Low,Low,Medium,Low,Medium,Low,Medium,High,Medium,Medium,High,High,Medium,Low,Medium,High,Low,Low,High,Low,Low,Medium,High,High,Medium,Medium,Medium,Low,High,Low,High,High,Low,High,High,Medium,Low,Low,Medium,Low,High,High,Low,Medium,High,Medium,High,Medium,Medium,Medium,High,Medium,Medium,High,Low,Low,Low,Medium,Medium,Medium,Low,High,Medium,High,Medium,High,High,High,Low,Medium,High,Medium,Low,High,Medium,Low,Medium,High,Low,Low,Low,High,Low,Low,High,Medium,High,Medium,High,Low,Medium,Medium,High,Medium,Medium,Medium,Medium,Medium,Low,Low,High,High,High,High,Medium,High,Medium,Medium,High,High,Low,Medium,High,Low,Medium,High,High,High,Medium,Medium,High,Low,High,High,High,Low,High,Medium
John$Sarah$Alex$Michael$Emma$Olivia$Daniel$Sophia$James$Isabella$Shannon Harrison$Peter Davila$Katherine Gray$Megan Miller$James Williams$Derrick Alexander$Courtney Clark$James Smith$James Reynolds$Brittany Sutton$Annette Medina$James Duncan$Donna Taylor$David Robertson$Susan Brown$Jessica Ortega$Jeremy Hall$Peter Jones$Michael Sampson$Daniel Erickson$David Aguilar$Benjamin Vance$Yolanda Chen$Kristina Douglas$Scott Davidson$Alexandra Harrington$Richard Johnson$Christopher Chapman$Jerry Browning$Carrie Page$Michelle Benjamin$James Woods$Angela Dunn$Nathan Riley$Shelby Mahoney$Andrea Frey$Justin Martin$Mark Hartman$Antonio Hansen$Lynn Anderson$Michael Cooley$Mitchell Sanders$Maria Cross$Lisa Castillo$Theresa Rodriguez$Kimberly Wood$Patricia Cox$Kimberly Blair$Jason Ramirez$Gail Dudley$John West$Patricia Carr$David Nunez$Collin Peterson$Rebecca Smith$Lisa Benjamin$Desiree Reyes$Megan Diaz$Joseph Adams$Sharon Watson$Tiffany Smith$Alexander Preston$Randall Hickman$David Hernandez$Michelle Jones$Tonya Gonzalez$Sarah Johnson$Grace Valencia$Sarah Young$Gerald Weber$Gregory Turner$Laura Cortez$Lori Miller$Lori Gomez PhD$Dawn Foster$Peter Welch$Maria Carter$Daniel Hood$Amanda Hernandez$Alyssa Schmidt$Taylor Merritt DVM$Alyssa Smith$Nathan Navarro$Lisa Zimmerman$Jeffrey Howard$Morgan Bell$Angelica Steele$Gregory Daniels$Eric Davis$Natalie Kelley$Ruth Davis$Emily Torres$Nancy Davis$Amanda Bowers$Alison Lang$Matthew Massey$James Anderson$Robert Howard$Rebecca Brown$Kimberly Harrison$Derek Parks$Jennifer Baker$Diana Schultz$Mrs. Jill Long$Heather Johnson$Robert Lowery$Angela Williams$Brent Burns$Melissa Barber$John Warner$Christopher Baxter$Courtney Haas$Sarah Ross$Manuel Baker$Jessica Lamb$Jaime Nguyen$Tina Chavez$Christina Thompson$Shari Harrell$Tracy Gibbs$David Hoffman$Robert Davis$Patricia Greer$James Stewart$Brent Mendoza$Dawn Taylor$Larry Brown$Miss Teresa Hernandez MD$Edward Baker$Diana Gould$Amy Rodriguez$Paul Hull$Allison Hamilton$John King$Tristan Avila$Connie Cooper$Judith Santos$Michaela Powell$Lawrence Roberts$Nicholas Robinson DDS$Jill Smith$Michael Burns$Adam Weaver$Melvin Mcgee$William Banks$Dawn Morton$Frank Dawson$Gregory Davila$Rebekah Finley$Robert Martinez$Steven Crawford$Leslie King$George Cannon$Adam Carlson$Stephanie Lawrence$Adam Blackwell$Andrew Owens$John Sexton$Jasmine Williams$Leon Nguyen$John White$Justin Martinez$Nathaniel Kemp$Jacob Murray$Anthony Green$Trevor Freeman$Michael Smith$William Hogan$Joshua Juarez$Keith Wu$Ryan Williams$Ronald Stewart$Ronald Schmidt$Courtney Bradley$Deanna Gonzalez$Darrell Adams$Michael Mata$Anthony Dunn$Jonathan Hodges$Jill Williams$Julia Russell$Shirley Jackson$Tonya Thompson$Brandon Williamson$Joseph Davis$Elizabeth Andersen$Jeffrey Meyers$Christopher Jones$Aimee Rogers$Alexis Bates$Michael Evans$Omar Gonzalez$Melissa Perry$Dawn Torres$Timothy Dean$Anna Rollins MD$Timothy Barrera$Susan Morris$Gordon Merritt$Kristy Rhodes$Kristi Cross$Ms. Marissa Ramirez$Paul Hickman$Mrs. Kathy Woodward$Alexis Horn$Shannon Harris DDS$Alicia Ortiz$Steven Wood$Alexis Walton$Martin Mcknight$Gina Palmer$Jean Moreno$David Anderson$Brian Huffman$Jose Liu$Cathy Pratt$Kathy Sandoval$Michael Webb$Ronnie Taylor$Matthew Miller$Shelly Hurley$Mr. Martin Dominguez MD$Jennifer Wiggins$Anthony Smith$John Lopez$Nathan Rodgers$Martin Walker$Jesus Wood$Kelly Bell$Kathryn Randall$Sarah Norris$Matthew Adams$William Wade$Brian Castro$Teresa Sanders$Richard Oneal$Christine Cooper$Michael Foster$Loretta Gonzalez$Douglas Ingram$Randy Anderson$Donna Shaw$Joseph Holt$Taylor Acosta$Danielle Scott$Melissa Aguirre$Cassandra Snyder$Kimberly Lambert$Rebecca Mendoza DDS$Michael Anderson$Hannah Gentry$Patrick Reed$Tiffany Huff$Thomas Lee$Justin Clark$Michael Martinez$Vincent Smith$Sean Hull$Sarah Welch$Mr. Stephen Gilmore$Barry Parker$Joshua Kane$Anthony Wright$Nathaniel Lopez$Darlene Fletcher$Christopher Moore$Benjamin White$Jenny Coleman$Michael Gomez$Caleb Serrano$William Carlson$Timothy Pruitt$Mario Johnston$Rebecca Kim$Joyce Williams$Cynthia Sloan$Patricia Williams$Michael Payne$Brooke Friedman$Daniel Mathis$Lynn Jennings$Kimberly Randolph$Jack Simmons$Daniel Mendez$Travis Lawson$Jason Horne DDS$Shawn Galloway$Thomas Barnes$Elizabeth Curry$Nicole Cunningham$Patrick Thompson$Marissa Stewart$Melissa Wilson$Jaime Glenn$Mark Castillo$Mr. Kent Stanton$Tyrone Phillips$Christopher Collins$David Rowe$Christopher Mccullough$Carla Rodriguez$Makayla Howard$Barbara White$Sarah Davis$Cody Donovan$Jessica Jenkins$Benjamin Alexander$Isaac Lopez$Ariana Morse$Brian Avery$Amy Lawson$Derek Choi$Paul Reese$Francisco Chang$Christian Knight$Andrew Wilkerson$Brandon Alvarez$Gary Young$Jessica Wright$Timothy Clements$Alexander Gordon DDS$James Martinez$Francisco Williams$Jordan Brooks$Kurt Boyd$Bryan Salazar$Mrs. Heather Roy$Kathleen Newton$Julian Fox$Kylie Hancock$Matthew Werner$Kelsey Bush$Brandon Dickerson$Jamie Allen$Taylor Smith$Elizabeth Chavez$Melissa Morris$Donna Hardin$Andrew Cook$Dr. Richard Wallace$Samuel Shaw$Mike Waters$Andrea Newman$Barry Jenkins$Laurie Johnson$John Coleman$John Carter$Mr. Devon Garrett$Jill Kelly$Richard Gonzalez$Alex White$Michael Gonzales$John Williams$Daniel Herrera$Jessica Richardson$Ian Glass$Heidi Simmons$Andrea Fuller$David Dunlap$Antonio Mitchell$Mariah Cole$Rhonda Ramos$Raymond Murillo$Andrea Bradley$Tina Velazquez$Bonnie Callahan$Eric Scott$Maria Leblanc$Michael Valenzuela$Robin Spears$David Owens$Elizabeth Clark$Beverly Fisher$Sarah Bailey$Kendra Ramirez$Diane Ross$Stephanie Mcfarland$Michelle Woods$David Ruiz$Jason Castro$Kathleen Montgomery$James Bennett$Kelsey Watkins$David Park$Christopher Poole$Rebecca Baxter$Virginia Daniel$Melissa Gordon$Brett Barrett$Brandon Townsend$Haley Robertson$Michelle Gonzalez$Gary Holland$Felicia Howard$Sean Walker$Brianna Mills$Michael Case$Felicia Houston$Kevin Wilson$Mary Vaughn$Maurice Martinez$Jonathon Perry$Rebecca Evans$Paul Williams$Tyler Boyer$Kristy Nichols$Darren Martin$Katelyn Morgan$Dennis Elliott$Jesus Henson$Robin Stewart$Lawrence Miller$Ronnie White$John Fox$Daniel Scott$Jonathan Mann$Bethany Andersen$Tiffany Moore$Sylvia Chavez$Gerald Reilly$Ashlee Wilcox$Lance Johnson$Patrick Gonzalez MD$Cole Gomez$Alejandro Gutierrez$Natalie Long$Abigail Ingram$Eileen Lee$Nancy Moore$Melanie Wilson$Gloria Henderson$Christopher Payne$John Franklin$Angel Stout$James Watkins$Candace Kelly$Zachary Daniel$Angel Howard$Heather Hill$Heather Gamble$Sean Levine$Brian Diaz$Catherine Koch$Anne Martin$Mary Warren$Amanda Bryant$Joel Ford$Mark Miller$Sarah Russell$Lisa Mitchell$William White$Jacqueline Garcia$Elizabeth Wright$Pamela Woods$Sydney Patterson$Lisa Johnson$Todd Jackson$Shelby Richards$Joseph Roberts$Samantha Burton$Cynthia Mcdonald$Kimberly Petty$Joshua Carpenter$Jessica Fuller$Andrea Barber$Brian Lyons$Tammy Fuentes$Robert Taylor$David Gonzalez$Steven Myers$Cassandra Perez$Jacqueline Eaton$Carrie Mccoy$Amy Fisher$Stephanie Reid$Reginald Hoover$Christina Russo$Raymond Howell$Angela Perez$Charles Aguilar$Caitlyn Green$Ronald Davis$Melissa Lucas$Heidi Leonard$Samantha Patton$Richard Swanson$Lauren Simpson$Kimberly Raymond$Marissa Raymond$Joyce Bishop$Michael Kelly$Peggy Hill$Derrick Love$Laura Stevens$Terri Potter$Veronica Saunders$Emily Townsend$James Long$Jennifer Dickson$Alexa West$Phillip Donovan$Monique King$Karl Murray$Julia Brooks$Lauren Montgomery$Nathan Wall$Kristin Macias$Samuel Smith$Bradley Stevens$Morgan Hampton$Lori Carrillo$Samantha Novak$Audrey Robinson$Lindsey Kerr$Cynthia Nguyen$Ryan Hood$Matthew Stevenson$Rhonda White$Larry Ramsey$Kimberly Anderson$Brian Miles$Kelly Baker$Wendy Miller$Michael Webster$Michelle Ryan$Justin Jennings$Norma Ward$Vincent Johnson$David Stone$Amy Evans$Caleb Walker$Stephen Ramirez$Nicholas Baxter$Raymond Smith$Roy Johnson$Ryan Vasquez$Justin Johnson$Kaylee Benjamin$Charles Murphy$Grant Henderson$Michael Woods$Michael Kane$Susan Benson$Timothy Armstrong$Cindy Harvey$Caitlin Carter$Ricky Johnson$Bryan Hoover$Elijah Wagner$Felicia Davis$Jonathan Hess$Michael Yoder$Samantha York$Joanna Martinez$Penny Hopkins$Justin Foster$Jennifer Morgan$Dalton Chen$Mrs. Amy Carney MD$Melissa Wang$Chelsea Porter$Cameron Bender$Vanessa Hall$Daniel Solomon$Deanna Jones$Alicia Young$Peter Figueroa$Jacob Thompson$Jonathon Woodward$Brian Hayes$Lisa Carroll$Cassandra Ryan$Terri Hayden$Taylor Burns$Andrew Jimenez$Wendy King$Luis Carter$Nicholas Jones$Tiffany Sanders$Tina Knight$Brittany Andrews$William Weber$Angela Ortiz$David Meyer$Michelle Aguilar$Travis Harrell$Craig Mccann$Scott Edwards$Kelly Cohen$David Diaz$Joseph Green$Henry Johnson$Keith Wilson$Jordan Chase$Kayla Solomon$Hayley Johnson$John Bender$William Christian$Michael Willis$James Simmons$Christopher Sullivan$Michelle Santos$Michael Walters$Jason Anderson$James Hoover$Julie Garza$Lisa Williams$Erica Thomas$Calvin Vargas$Molly Jones$Shannon Hogan$James Fields$Arthur Johnson$Collin Edwards$Kimberly Smith$Mr. Clinton Camacho$Taylor Moyer$David Jimenez$Kyle Coleman$Marvin Cardenas$Eddie Robertson$Christopher Diaz$Christopher Taylor$Brenda Bell$Ashley Nguyen$Michael Bailey$Maria Scott$Katherine Mclaughlin$Karen Cruz$Jodi Taylor$Thomas Mcgrath$Alec Peterson$Kathy Bailey$Karen Wolf$Mary Jones$Lisa Houston$Ashley Jordan$Lonnie Williams$Michael Poole$David Martinez$Eduardo Miller$Kristine Williams$Audrey Woods$Lauren Brown$Stephanie Merritt$Rebecca Jones$Isaiah Arnold$Andrea Frey$Andrew Dudley$Kenneth Jones$Jane Griffith$Jeff Phillips$Dawn Edwards$Paige Campbell$Belinda Kim$Christopher Cruz$Ruben Steele$Bradley Martinez$Alison Williams$Scott Ferguson$David Brown$Joseph Smith$Renee Scott$Aimee Green$Ricky Jenkins$Kelly Allen MD$Sean Smith$Robert Johnson$Susan Russell$Ryan West$Christina Fitzgerald$Susan Roberson$Jessica Banks$Jodi Rogers$Michelle Clay$Jacob Bean$Robert Harper$Valerie Gibson$Michelle Graham$Seth Johnson$John Jones$Julia Sanchez$Justin Sharp$Thomas Yoder$Christine Mullins$Timothy Mcbride$Deborah Reyes$Chad Downs$William Hill$Makayla Rhodes$Clayton Jones$Sean Hernandez$Christine Young$Brian Hale$Sandra Hart$Christine Curtis$Tara Johnson$Stephanie Snyder$Miguel Leblanc$Christina Mcintyre$John Weber$Timothy Austin$Jeffrey Sullivan$Michael Noble$Christine Shah$Lisa Maynard$Lisa Lynch$Angela Warren$Mary Benson$Yvonne Krueger$Keith Bailey$Barbara Case$Jamie Torres$Justin Jacobs$Kevin Reynolds$Michelle Kelly$Terry Hernandez$Aaron Duarte$Micheal Perez$Troy Bradford$Bobby Wilkinson$Juan Lopez$Virginia Medina$Leah Holmes$Todd Brooks$Madeline Rush$Ronnie Lee$Nicole Frederick$Jason Adams$Mallory Fletcher$David Cummings$Kelly Suarez$Drew Morse$Lauren Stephens$Penny Miller$Paula Stewart$Jonathan Johnson$Laura Ross$Brandy Wilson$Brittany Briggs$Carl Coleman$Crystal Chandler$Elizabeth Nichols$Jesse Barber$Julie Jackson$Cindy Morales$Ashley Franco$Kimberly Calderon$Lisa Brooks$Destiny Todd$Dawn Luna$Jacob Yoder$Martha Moody$James Torres$Joshua Robertson$Shelly Stuart$Julie Williams$Tamara Jones$Todd Orozco$Jeffrey Torres$Chad Colon$Alan Williams$Cameron Austin$Dawn Nguyen$Andrea Phillips$Robert Bishop$Melanie Mckinney$Joseph Ellis$Jennifer Smith$Vickie Holloway$Nancy Munoz$David Taylor$Amber Gray$Christian Barr$Kimberly Harrison$Mark Fleming$Felicia Carpenter$Rebecca Kelly$Aaron Walls$Mark King$James Macdonald$Alexander Thompson$Kaitlin Walton$Ashley Kaufman$Megan Bernard$Kelly Harper$Daniel White$Justin Castro$John Odonnell$Whitney Tapia$Jeff Lawrence$Jeremy Shields$Matthew Davies$Christine Hamilton$Crystal Proctor$Tracy Kelley$Victoria Mcbride$Ellen Cross MD$David Stevens$Frank Brown DDS$Jenna Price$Deborah Barajas$Richard Howard Jr.$Anita Dougherty$Alicia Watson$Deborah Hunter$Morgan Gilbert$Taylor Crawford$Danny Sanchez$Cory Rosario DDS$Kyle Perez$Kelly Gibson MD$Angela Garcia$Dylan Vaughan$Kevin Santiago$Terry Rodriguez$Chad Mason$Jessica Ferguson$Andrew Schroeder$Jeffrey Garcia$Jason Hood$Sandra Leon$Tyler Mccormick$Megan Murphy$Charles Vincent$Mrs. Cindy Sharp DVM$Sarah Dixon$Teresa Rodriguez$Shannon Spencer$Darlene Tapia$Ryan Ball$Anita Berger$Tom Bradley$Melinda Cummings$Melissa Donaldson$Charles Pearson$Isaiah Moore$Jonathan Ramirez$Mrs. Melanie Mueller$Ms. Heather Dean$David Malone$Melissa Brown$Jason Woods$Rachel Diaz$Michael Jones$Taylor Mcgee$Christopher Ray$Alyssa Berg MD$Jordan Thornton$Dr. James Henry DDS$James Stevens$Kevin Marquez$Colleen Porter$Christian Odom$Calvin Macias$Kim Fischer$Travis Schultz$Bonnie Morris$Tiffany Morris$Paul Poole$Richard Perez$Bernard Whitaker$Melinda Miller$Christina Gonzales$Maria Gray$Mary Bennett$Dr. Erik Pineda$Sandra Burns$Patricia Hunt$Erika Kennedy$Timothy Newman$Tanya Bowen$Rhonda Davenport$Cheryl Brown$Angela Bridges$Brandon Rasmussen$Ryan Beltran$Allison Novak$Matthew Winters$Kirsten Davis$Paige Turner$Aimee Christensen$Jessica Howard$Lisa Zhang$Jonathan Daniel$Cheyenne Oliver$Brianna Henderson$Mark Sanchez$Melissa Nguyen$Jeff Carney$Tammy Tanner$Donna Robinson$Eric Wilson$Linda Armstrong$Russell Jones$Darlene Burton$Faith Johnson$Nathan Miller$Donna Fowler$Whitney Jefferson$Shane Sanders$Felicia Cline$Jennifer Clark$Miss Carla Coleman MD$William Nelson$Crystal Brown$Erica Miller$Emily Martin$Erica Miller$Wesley May$Christopher Atkinson$Blake Martinez$Joy Henderson$Mary Ramos$Colleen Sanchez$David Cruz$Ralph Becker$Denise Coleman$Samantha Mendoza$Sean Lyons$Anthony Smith$Deborah Hernandez$Kristi Price$Alex Douglas$Ian Mcdonald$David Bauer$Steven Hill$Linda Beasley$Maria Edwards$Megan Hutchinson$Jaime Simon$Thomas Freeman$Nancy Gibson$Holly Leon$Travis Pierce$Nina Fowler$Kristen Galloway$Raven Taylor$Samuel Robinson$Christina Johnson$Holly Spencer$Jessica Davies$Daniel Sullivan$Richard Franklin$Samantha Klein$Becky Perkins$Kimberly Pena$Rebecca Burnett$Anna Martinez$James Garcia$Monica Johnson$Shannon Porter$Kenneth Murray$Amy Stout$Joseph Sherman$Maria Walls

In [11]:
#  get_dummies(): This method converts each unique string into a separate one-hot encoded column for modeling.
print(df["Gender"].str.get_dummies())

     Female  Male
0         0     1
1         1     0
2         0     1
3         0     1
4         1     0
..      ...   ...
995       0     1
996       1     0
997       0     1
998       0     1
999       1     0

[1000 rows x 2 columns]

In [15]:
# startswith(): This method checks whether each string begins with the specified prefix.
print(df["Name"].str.startswith("S"))
print(df["Name"].str.startswith("J"))

0      False
1       True
2      False
3      False
4      False
       ...
995    False
996    False
997      NaN
998    False
999    False
Name: Name, Length: 1000, dtype: object
0       True
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997      NaN
998     True
999    False
Name: Name, Length: 1000, dtype: object

In [18]:
# endswith(): This method checks whether each string ends with the specified suffix.
print(df['Name'].str.endswith("a"))
print(df['Name'].str.endswith("s"))

0      False
1      False
2      False
3      False
4       True
       ...
995    False
996    False
997      NaN
998    False
999    False
Name: Name, Length: 1000, dtype: object
0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997      NaN
998    False
999     True
Name: Name, Length: 1000, dtype: object

In [20]:
# replace(): This method replaces occurrences of a specific substring or pattern with a new value.

print(df['Name'].str.replace('John', 'Emily'))

0               Emily
1               Sarah
2                Alex
3             Michael
4                Emma
            ...
995    Kenneth Murray
996         Amy Stout
997               NaN
998    Joseph Sherman
999       Maria Walls
Name: Name, Length: 1000, dtype: object

In [22]:
# repeat(): This method duplicates each string a given number of times.
print(df['Name'].str.repeat(2))

0                          JohnJohn
1                        SarahSarah
2                          AlexAlex
3                    MichaelMichael
4                          EmmaEmma
                   ...
995    Kenneth MurrayKenneth Murray
996              Amy StoutAmy Stout
997                             NaN
998    Joseph ShermanJoseph Sherman
999          Maria WallsMaria Walls
Name: Name, Length: 1000, dtype: object

In [24]:
# count(): This method counts how many times a specific substring or pattern appears in each string.

print(df['Name'].str.count('a'))

0      0.0
1      2.0
2      0.0
3      1.0
4      1.0
      ...
995    1.0
996    0.0
997    NaN
998    1.0
999    3.0
Name: Name, Length: 1000, dtype: float64

In [26]:
# find(): This method returns the index of the first occurrence of a pattern within each string.
print(df['Name'].str.find('a'))

0      -1.0
1       1.0
2      -1.0
3       4.0
4       3.0
       ...
995    12.0
996    -1.0
997     NaN
998    12.0
999     1.0
Name: Name, Length: 1000, dtype: float64

In [28]:
# findall(): This method returns a list of all occurrences of a pattern found in each string.
print(df['Name'].str.findall('a'))

0             []
1         [a, a]
2             []
3            [a]
4            [a]
         ...
995          [a]
996           []
997          NaN
998          [a]
999    [a, a, a]
Name: Name, Length: 1000, dtype: object

In [48]:
# islower(): This method checks whether all characters in each string are lowercase.
print(df['Name'].str.islower())

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997      NaN
998    False
999    False
Name: Name, Length: 1000, dtype: object

In [32]:
# isupper(): This method checks whether all characters in each string are uppercase.
print(df['Name'].str.isupper())

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997      NaN
998    False
999    False
Name: Name, Length: 1000, dtype: object

In [49]:
# isnumeric(): This method checks whether each string contains only numeric characters.
print(df["Name"].str.isnumeric())

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997      NaN
998    False
999    False
Name: Name, Length: 1000, dtype: object

In [38]:
# swapcase(): This method swaps uppercase letters to lowercase and lowercase letters to uppercase for each string.
print(df["Name"].str.swapcase())

0                jOHN
1               sARAH
2                aLEX
3             mICHAEL
4                eMMA
            ...
995    kENNETH mURRAY
996         aMY sTOUT
997               NaN
998    jOSEPH sHERMAN
999       mARIA wALLS
Name: Name, Length: 1000, dtype: object

In [50]:
# print(df.iloc[1:21]["Gender"])
# print(df.iloc[1:21]["Name"])

print(df[1:21])

    StudentID               Name  Gender  AttendanceRate  StudyHoursPerWeek  \
1         2.0              Sarah  Female            90.0               20.0
2         3.0               Alex    Male            78.0               10.0
3         4.0            Michael    Male            92.0               25.0
4         5.0               Emma  Female             NaN               18.0
5         6.0             Olivia  Female            95.0               30.0
6         7.0             Daniel    Male            70.0                8.0
7         8.0             Sophia  Female             NaN               17.0
8         9.0              James    Male            82.0               12.0
9        10.0           Isabella  Female            91.0               22.0
10     2824.0   Shannon Harrison    Male            88.0               25.0
11     7912.0       Peter Davila    Male            85.0               20.0
12     4611.0     Katherine Gray  Female            91.0               18.0
13     6514.0       Megan Miller    Male            90.0                8.0
14        NaN     James Williams    Male            70.0               20.0
15     2139.0  Derrick Alexander    Male             NaN               18.0
16        NaN     Courtney Clark     NaN            95.0               25.0
17     8573.0        James Smith  Female            88.0               12.0
18     5386.0     James Reynolds    Male            92.0               22.0
19     3340.0    Brittany Sutton  Female            78.0               25.0
20     6930.0     Annette Medina    Male            78.0               12.0

    PreviousGrade  ExtracurricularActivities ParentalSupport  FinalGrade  \
1            85.0                        2.0          Medium        87.0
2            65.0                        0.0             Low        68.0
3            90.0                        3.0            High        92.0
4            82.0                        2.0          Medium        85.0
5            88.0                        1.0            High         NaN
6            60.0                        0.0             Low        62.0
7            77.0                        1.0          Medium        78.0
8            70.0                        2.0             Low        72.0
9            86.0                        3.0            High        88.0
10           90.0                        0.0             NaN        87.0
11            NaN                        3.0             Low        88.0
12           78.0                        0.0             Low        62.0
13           85.0                        1.0          Medium        88.0
14           70.0                        2.0             Low        88.0
15           85.0                        3.0            High        62.0
16           82.0                        2.0             Low        68.0
17           90.0                        1.0            High        92.0
18           88.0                        3.0             Low        78.0
19           70.0                        2.0          Medium        88.0
20           77.0                        2.0            High        87.0

    Study Hours  Attendance (%) Online Classes Taken
1           2.2            70.0                 True
2           4.6            92.0                False
3           2.9            96.0                False
4           4.1            97.0                 True
5           2.8            97.0                False
6           4.5            96.0                False
7           1.0            70.0                 True
8           3.6            50.0                False
9           2.9            59.0                 True
10          3.4            84.0                 True
11          0.1            62.0                False
12          1.7            59.0                 True
13          1.3            52.0                False
14          4.4            73.0                 True
15          1.4            90.0                False
16          2.7            65.0                 True
17          4.1            70.0                False
18          2.0            91.0                False
19          2.1            87.0                False
20          0.8            60.0                False

In [57]:
import pandas as pd

data = pd.read_csv("student_performance_updated_1000.csv", chunksize=5)

chunk = next(data)
print(chunk)

   StudentID     Name  Gender  AttendanceRate  StudyHoursPerWeek  \
0        1.0     John    Male            85.0               15.0
1        2.0    Sarah  Female            90.0               20.0
2        3.0     Alex    Male            78.0               10.0
3        4.0  Michael    Male            92.0               25.0
4        5.0     Emma  Female             NaN               18.0

   PreviousGrade  ExtracurricularActivities ParentalSupport  FinalGrade  \
0           78.0                        1.0            High        80.0
1           85.0                        2.0          Medium        87.0
2           65.0                        0.0             Low        68.0
3           90.0                        3.0            High        92.0
4           82.0                        2.0          Medium        85.0

   Study Hours  Attendance (%)  Online Classes Taken
0          4.8            59.0                 False
1          2.2            70.0                  True
2          4.6            92.0                 False
3          2.9            96.0                 False
4          4.1            97.0                  True

In [60]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [24, 27, 22, 32],
        'Score': [85, 90, 88, 78]}
df = pd.DataFrame(data)
print(df['Age'].mean())

26.25

In [62]:
import pandas as pd
data = {'A': [10, 20, 30], 'B': [40, 50, 60]}
df = pd.DataFrame(data)
print(df.loc[0, 'B'])

40

In [64]:
import pandas as pd
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df.iloc[1:3, 0])

1    2
2    3
Name: A, dtype: int64

In [66]:
import pandas as pd
import numpy as np
data = {'A': [1, 2, np.nan, 4], 'B': [np.nan, 2, 3, 4]}
df = pd.DataFrame(data)
result = df.isnull().sum()
print(result)

A    1
B    1
dtype: int64

In [68]:
import pandas as pd
import numpy as np
data = {'A': [1, np.nan, 3], 'B': [4, 5, np.nan]}
df = pd.DataFrame(data)
df.dropna(axis=1, how='any', inplace=True)
print(df)

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [70]:
import pandas as pd
import numpy as np

data = {'A': [np.nan, 2, np.nan, 4], 'B': [1, np.nan, 3, 4]}
df = pd.DataFrame(data)
df['A'] = df['A'].fillna(df['A'].mean())
print(df)

     A    B
0  3.0  1.0
1  2.0  NaN
2  3.0  3.0
3  4.0  4.0

In [73]:
import pandas as pd
import numpy as np

data = {'A': [1, np.nan, 3], 'B': [4, np.nan, np.nan]}
df = pd.DataFrame(data)
df.dropna(how='all', inplace=True)
print(df)

     A    B
0  1.0  4.0
2  3.0  NaN

In [75]:
import pandas as pd 
data = {'A': ['foo', 'bar', 'foo', 'bar'], 'B': [1, 2, 3, 4]}
df = pd.DataFrame(data)
result = df.groupby('A')['B'].transform('mean')
print(result)

0    2.0
1    3.0
2    2.0
3    3.0
Name: B, dtype: float64

In [77]:
import pandas as pd 
data = {'A': ['foo', 'foo', 'bar', 'bar'], 
        'B': ['one', 'two', 'one', 'two'], 
        'C': [1, 2, 3, 4]}
df = pd.DataFrame(data)
result = df.groupby(['A', 'B']).sum()
print(result)

         C
A   B
bar one  3
    two  4
foo one  1
    two  2

In [79]:
import pandas as pd 
data = {'A': ['X', 'X', 'Y', 'Y'], 'B': ['one', 'two', 'one', 'two'], 'C': [10, 20, 30, 40]}
df = pd.DataFrame(data)
result = df.pivot_table(values='C', index='A', columns='B', aggfunc='sum')
print(result)

B  one  two
A
X   10   20
Y   30   40

In [86]:
import pandas as pd
data = {'Group': ['A', 'A', 'B', 'B'], 'Values': [10, 30, 20, 40]}
df = pd.DataFrame(data)
# df.groupby('Group').filter(lambda x: x['Values'] > 20)['Values'].sum()
df[df['Values'] > 20].groupby('Group')['Values'].sum()
# df.groupby('Group')['Values'].sum().apply(lambda x: x > 20)

Group
A    30
B    40
Name: Values, dtype: int64

In [88]:
import pandas as pd 
data = {'A': [1, 1, 2], 'B': [3, 4, 5]}
df = pd.DataFrame(data)
result = df.groupby('A').describe()
print(result)

      B
  count mean       std  min   25%  50%   75%  max
A
1   2.0  3.5  0.707107  3.0  3.25  3.5  3.75  4.0
2   1.0  5.0       NaN  5.0  5.00  5.0  5.00  5.0

In [89]:
import pandas as pd
data = {'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]}
df = pd.DataFrame(data)
result = df[['A', 'B']].agg(['sum', 'mean'])
print(result)

        A     B
sum   6.0  15.0
mean  2.0   5.0